name: MySQL Query Automation

on:
  push:
    branches:
      - main

jobs:
  mysql-query:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install MySQL Client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Test MySQL Connectivity
        run: |
          ping -c 4 3.86.153.167 || echo "Failed to reach MySQL server"
          nc -zv 3.86.153.167 3307 || echo "Port 3307 is not open"

      - name: Retrieve MySQL Credentials
        run: |
          SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id mysql_password_setup --query SecretString --output text)
          echo "DB_USER=$(echo $SECRET_JSON | jq -r '.username')" >> $GITHUB_ENV
          echo "DB_PASS=$(echo $SECRET_JSON | jq -r '.password')" >> $GITHUB_ENV

      - name: Run MySQL Queries
        env:
          DB_HOST: "3.86.153.167"
          DB_PORT: "3307"
        run: |
          mysql --host=$DB_HOST --port=$DB_PORT --user=$DB_USER --password="$DB_PASS" --database=employees -e "
          SELECT MIN(YEAR(hire_date)) AS first_hire_year, MAX(YEAR(hire_date)) AS latest_hire_year FROM employees;
          SELECT * FROM employees WHERE gender = 'M' ORDER BY birth_date ASC;
          SELECT * FROM employees ORDER BY birth_date ASC;
          SELECT * FROM employees WHERE gender = 'M';
          SELECT * FROM employees WHERE gender = 'F';
          CREATE USER 'admin'@'%' IDENTIFIED BY 'Admin@123';
          GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
          FLUSH PRIVILEGES;
          SELECT * FROM dept_emp ORDER BY birth_date ASC;
          SELECT MIN(YEAR(from_date)) AS first_from_date, MAX(YEAR(from_date)) AS latest_to_date FROM dept_emp;
          "
