name: MySQL Query Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-mysql-query:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install MySQL Client & jq
        run: |
          sudo apt update
          sudo apt install -y mysql-client jq

      - name: Fetch MySQL Credentials from AWS Secrets Manager
        run: |
          AWS_SECRET=$(aws secretsmanager get-secret-value --secret-id mysql_password_setup --query SecretString --output text)
          echo "DB_USER=$(echo $AWS_SECRET | jq -r '.username')" >> $GITHUB_ENV
          echo "DB_PASS=$(echo $AWS_SECRET | jq -r '.password')" >> $GITHUB_ENV
        env:
          AWS_REGION: "us-east-1"  # Change this to your region
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Execute MySQL Query
        run: |
          mysql --host=your-mysql-endpoint --port=3307 --user=$DB_USER --password=$DB_PASS --database=employees -e "SELECT * FROM employees LIMIT 5;"
