name: Run MySQL Queries via AWS SSM

on:
  push:
    branches:
      - main

jobs:
  run-mysql-query:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug GitHub Secrets
        run: |
          echo "Checking AWS Secrets..."
          echo "AWS_REGION=${{ secrets.AWS_REGION }}"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          if [[ -z "${{ secrets.AWS_REGION }}" ]]; then
            echo "ERROR: AWS_REGION is not set!"
            exit 1
          fi

      - name: Verify AWS CLI Installation
        run: |
          if ! command -v aws &> /dev/null; then
            echo "AWS CLI not found, installing..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update
          else
            echo "AWS CLI is already installed."
          fi
          aws --version  # Confirm AWS CLI version

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
          aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}"
          aws configure set region "${AWS_REGION}"
          
      - name: Verify AWS Configuration
        run: |
          echo "AWS_REGION is set to: $AWS_REGION"
          aws sts get-caller-identity  # Verify IAM credentials are correct

      - name: Run MySQL Query via AWS SSM
        run: |
          echo "Executing MySQL query on EC2 instance..."
          aws ssm send-command \
            --instance-ids i-0c27818662c8919c3 \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id mysql_password_setup --query SecretString --output text --region $AWS_REGION)",
              "DB_USER=$(echo $SECRET_JSON | jq -r .username)",
              "DB_PASS=$(echo $SECRET_JSON | jq -r .password)",
              "mysql -u $DB_USER -p$DB_PASS -h localhost -P 3307 -D employees -e \"SELECT * FROM employees LIMIT 5;\""
            ]' \
            --timeout-seconds 3600
