name: Run MySQL Queries via AWS SSM

on:
  push:
    branches:
      - main

jobs:
  run-mysql-query:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch AWS Secrets
        run: |
          SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id mysql_password_setup --query SecretString --output text)
          echo "DB_USER=$(echo $SECRET_JSON | jq -r '.username')" >> $GITHUB_ENV
          echo "DB_PASS=$(echo $SECRET_JSON | jq -r '.password')" >> $GITHUB_ENV

      - name: Run MySQL Query via AWS SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "[{\"Key\":\"InstanceIds\",\"Values\":[\"i-0c27818662c8919c3\"]}]" \
            --parameters "commands=[\"mysql -u $DB_USER -p'$DB_PASS' -h localhost -P 3307 -D employees -e 'SELECT * FROM employees LIMIT 5;'\" ]" \
            --region us-east-1
